<?php 

$positions = [
[
    'apartment_id' => 1,
    'postal_code' => 25121,
    'city' => 'Brescia',
    'province' => 'BS',
    'street' =>'Attilio Franchi',
],
[
    'apartment_id' => 2,
    'postal_code' => 66040,
    'city' => 'Roccascalegna',
    'province' => 'CH',
    'street' => 'Via Roma',
],
[
    'apartment_id' => 3,
    'postal_code' => 98023,
    'city' => 'Furci Siculo',
    'province' => 'ME',
    'street' => 'Via Cesare Battisti',
],
[
    'apartment_id' => 4,
    'postal_code' => 66052,
    'city' => 'Gissi',
    'province' => 'CH',
    'street' => 'Via dello Stadio',
],
[
    'apartment_id' => 5,
    'postal_code' => 80129,
    'city' => 'Napoli',
    'province' => 'NA',
    'street' => 'Via Pigna',
],
[
    'apartment_id' => 6,
    'postal_code' => 53100,
    'city' => 'Peruzzo',
    'province' => 'SI',
    'street' => 'Strada della Peruzza',
],
[
    'apartment_id' => 7,
    'postal_code' => 52025,
    'city' => 'Pestello',
    'province' => 'AR',
    'street' => 'Via Reno',
],
[
    'apartment_id' => 8,
    'postal_code' => 34149,
    'city' => 'Gropada',
    'province' => 'TS',
    'street' => 'Piazzetta del Pozzo',
],
[
    'apartment_id' => 9,
    'postal_code' => 10090,
    'city' => 'Reano',
    'province' => 'TO',
    'street' => 'Via S. Rocco',
],
[
    'apartment_id' => 10,
    'postal_code' => 20080,
    'city' => 'Riazzolo',
    'province' => 'MI',
    'street' => 'Str. per Riazzolo',
],
[
    'apartment_id' => 11,
    'postal_code' => 20862,
    'city' => 'Arcore',
    'province' => 'MB',
    'street' => 'Via A. Casati',
],
[
    'apartment_id' => 12,
    'postal_code' => 20862,
    'city' => 'Arcore',
    'province' => 'MB',
    'street' => 'Viale S. Martino',
],
[
    'apartment_id' => 13,
    'postal_code' => 20862,
    'city' => 'Arcore',
    'province' => 'MB',
    'street' => 'Via Francesco Caglio',
],
[
    'apartment_id' => 14,
    'postal_code' => 20862,
    'city' => 'Arcore',
    'province' => 'MB',
    'street' => 'Via Alessandro Manzoni',
],
[
    'apartment_id' => 15,
    'postal_code' => 30100,
    'city' => 'Marghera',
    'province' => 'VE',
    'street' => 'Via Botteghino',
],
[
    'apartment_id' => 16,
    'postal_code' => 30100,
    'city' => 'Marghera',
    'province' => 'VE',
    'street' => 'Via della Rinascita',
],
[
    'apartment_id' => 17,
    'postal_code' => 30100,
    'city' => 'Marghera',
    'province' => 'VE',
    'street' => 'Via Pietro Zerman',
],
[
    'apartment_id' => 18,
    'postal_code' => 30100,
    'city' => 'Marghera',
    'province' => 'VE',
    'street' => 'Via Delle Macchina',
],
[
    'apartment_id' => 19,
    'postal_code' => 30100,
    'city' => 'Marghera',
    'province' => 'VE',
    'street' => 'Via Elettricità',
],
[
    'apartment_id' => 20,
    'postal_code' => 30100,
    'city' => 'Marghera',
    'province' => 'VE',
    'street' => 'Via Alessandro Volta',
],
[
    'apartment_id' => 21,
    'postal_code' => 00055,
    'city' => 'Ladispoli',
    'province' => 'RM',
    'street' => 'Via La Spezia',
],
[
    'apartment_id' => 22,
    'postal_code' => 00055,
    'city' => 'Ladispoli',
    'province' => 'RM',
    'street' => 'Via Palermo',
],
[
    'apartment_id' => 23,
    'postal_code' => 00055,
    'city' => 'Ladispoli',
    'province' => 'RM',
    'street' => 'Via Fiume',
],
[
    'apartment_id' => 24,
    'postal_code' => 10060,
    'city' => 'Macello',
    'province' => 'TO',
    'street' => 'Viale Rimembranza',
],
[
    'apartment_id' => 25,
    'postal_code' => 10060,
    'city' => 'Macello',
    'province' => 'TO',
    'street' => 'Via Buriasco',
],
[
    'apartment_id' => 26,
    'postal_code' => 10060,
    'city' => 'Macello',
    'province' => 'TO',
    'street' => 'Via Campanile',
],
[
    'apartment_id' => 27,
    'postal_code' => 89065,
    'city' => 'Motta San Giovanni',
    'province' => 'RC',
    'street' => 'Via Antonio Caserta',
],
[
    'apartment_id' => 28,
    'postal_code' => 89065,
    'city' => 'Motta San Giovanni',
    'province' => 'RC',
    'street' => 'Via Annunziato Laganà',
],
[
    'apartment_id' => 29,
    'postal_code' => 66054,
    'city' => 'Vasto',
    'province' => 'CH',
    'street' => 'Via Marco Polo',
],
[
    'apartment_id' => 30,
    'postal_code' => 66054,
    'city' => 'Vasto',
    'province' => 'CH',
    'street' => 'Via S.Rocco',
],
[
    'apartment_id' => 31,
    'postal_code' => 66054,
    'city' => 'Vasto',
    'province' => 'CH',
    'street' => 'Piazza del Popolo',
],
[
    'apartment_id' => 32,
    'postal_code' => 66054,
    'city' => 'Vasto',
    'province' => 'CH',
    'street' => 'Piazza del Popolo',
],
[
    'apartment_id' => 33,
    'postal_code' => 35030,
    'city' => 'Caselle',
    'province' => 'PD',
    'street' => 'Via Pelosa',
],
[
    'apartment_id' => 34,
    'postal_code' => 35030,
    'city' => 'Caselle',
    'province' => 'PD',
    'street' => 'Via Monti',
],
[
    'apartment_id' => 35,
    'postal_code' => 98051,
    'city' => 'Barcellona Pozzo di Gotto',
    'province' => 'ME',
    'street' => 'Via Militi',
],
[
    'apartment_id' => 36,
    'postal_code' => 98051,
    'city' => 'Barcellona Pozzo di Gotto',
    'province' => 'ME',
    'street' => 'Via Giuseppe Parini',
],
[
    'apartment_id' => 37,
    'postal_code' => 98051,
    'city' => 'Barcellona Pozzo di Gotto',
    'province' => 'ME',
    'street' => 'Via Monti',
],
[
    'apartment_id' => 38,
    'postal_code' => 25072,
    'city' => 'Bagolino',
    'province' => 'BS',
    'street' => 'Via Forno',
],
[
    'apartment_id' => 39,
    'postal_code' => 25072,
    'city' => 'Bagolino',
    'province' => 'BS',
    'street' => 'Via Mignano',
],
[
    'apartment_id' => 40,
    'postal_code' => 25072,
    'city' => 'Bagolino',
    'province' => 'BS',
    'street' => 'Via Madonna Di S.Luca',
],
]
